const ERR_USER_NOT_FOUND = 'USER_NOT_FOUND';
const ERR_INVALID_PASSWORD = 'INVALID_PASSWORD';
const ERR_INVALID_TOKEN = 'TOKEN_ERROR';

const ERR_DUPLICATE_EMAIL = 'Email already exists';

module.exports = {
  ERR_USER_NOT_FOUND,
  ERR_INVALID_PASSWORD,
  ERR_INVALID_TOKEN,
  ERR_DUPLICATE_EMAIL,
};
